#!/bin/bash
readarray -t cans <<< $(ip link | awk '/^[0-9]+: can/ {print $2, $9}' | tr -d ' ')
for can in ${cans[@]}; do
    can_interface="$(echo ${can} | cut -d ':' -f 1)"
    if [[ $(echo ${can} | cut -d ':' -f 2) == "DOWN" ]]; then
        sudo ip link set ${can_interface} up type can bitrate 1000000
        echo -e "\e[0;34m${can_interface}\e[0;0m is \e[0;32mUP\e[0;0m"
    else
        echo -e "\e[0;34m${can_interface}\e[0;0m is already \e[0;32mUP\e[0;0m"
    fi
done
