DEFINE_GFC_NAME	0 MOB0 2
DEFINE_GFC_NAME	1 MOB1 2
DEFINE_GFC_NAME	2 MOB2 2
DEFINE_GFC_NAME	3 MOB3 2
DEFINE_GFC_NAME	4 MOB4 2
DEFINE_GFC_NAME	5 MOB5 2
DEFINE_GFC_NAME	6 MOB6 2
DEFINE_GFC_NAME	7 MOB7 2
DEFINE_GFC_NAME	8 MOB8 2
DEFINE_GFC_NAME	9 MOB9 2

// この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	10 MOB10 1
DEFINE_GFC_NAME	11 MOB11 1
DEFINE_GFC_NAME	12 MOB12 1
DEFINE_GFC_NAME	13 MOB13 1
DEFINE_GFC_NAME	14 MOB14 1
DEFINE_GFC_NAME	15 MOB15 1
DEFINE_GFC_NAME	16 MOB16 1
DEFINE_GFC_NAME	17 MOB17 1
DEFINE_GFC_NAME	18 MOB18 1
DEFINE_GFC_NAME	19 MOB1 1


DEFINE_GFB_NAME	20 PVV0_YORIMICHI
DEFINE_GFB_NAME	21 PVV100_BATH
DEFINE_GFB_NAME	22 ALCHEMY_RECIPE
DEFINE_GFB_NAME	23 WALROSS_CURRY
DEFINE_GFB_NAME	24 PVV105_CITY_ELEC
DEFINE_GFB_NAME	25 PVV105_CITY_SLAM_BST
DEFINE_GFB_NAME	26 TTR_PLAYED
DEFINE_GFB_NAME	27 TTR_PLAYED_BAR
DEFINE_GFB_NAME	28 OMORASHI
DEFINE_GFB_NAME	29 OMORASHI_BAR

DEFINE_GFB_NAME 90 REPLACE_BATTLE_PICTURE_OLD

GFC_SEPARATOR 20 PVV
DEFINE_GFC_NAME	20	PHASE
DEFINE_GFC_NAME	21	PHASEV

GFC_SEPARATOR 30 ノエル
DEFINE_GFC_NAME	30	NOE0 // ナイチンゲールさん好感度
DEFINE_GFC_NAME	31	NOE1
DEFINE_GFC_NAME	32	NOE2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	33	NOE3 2

GFC_SEPARATOR 34 アリス
DEFINE_GFC_NAME	34	ALC0 // ナイチンゲールさん好感度
DEFINE_GFC_NAME	35	ALC1
DEFINE_GFC_NAME	36	ALC2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	37	ALC3 2

GFC_SEPARATOR 38 ナイチンゲールさん
DEFINE_GFC_NAME	38	NIG0 // ナイチンゲールさん好感度
DEFINE_GFC_NAME	39	NIG1
DEFINE_GFC_NAME	40	NIG2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	41	NIG3 2

GFC_SEPARATOR 42 イクシャ
DEFINE_GFC_NAME	42	IXA0 // ナイチンゲールさん好感度
DEFINE_GFC_NAME	43	IXA1
DEFINE_GFC_NAME	44	IXA2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	45	IXA3 2

GFC_SEPARATOR 46 衛兵
DEFINE_GFC_NAME	46	EIH0 // 好感度
DEFINE_GFC_NAME	47	EIH1
DEFINE_GFC_NAME	48	EIH2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	49	EIH3 2

GFC_SEPARATOR 50 チルダ
DEFINE_GFC_NAME	50	TLD0 // 好感度
DEFINE_GFC_NAME	51	TLD1
DEFINE_GFC_NAME	52	TLD2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	53	TLD3 2

GFC_SEPARATOR 54 プリムラ
DEFINE_GFC_NAME	54	PRM0 // 好感度
DEFINE_GFC_NAME	55	PRM1
DEFINE_GFC_NAME	56	PRM2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	57	PRM3 2

GFC_SEPARATOR 58 アルマ
DEFINE_GFC_NAME	58	ALM0 // 好感度
DEFINE_GFC_NAME	59	ALM1
DEFINE_GFC_NAME	60	ALM2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	61	ALM3 2

GFC_SEPARATOR 62 ヴァーロス

DEFINE_GFC_NAME	62	WLR0 // 好感度
DEFINE_GFC_NAME	63	WLR1
DEFINE_GFC_NAME	64	WLR2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	65	WLR3 2

GFC_SEPARATOR 66 オストレア

DEFINE_GFC_NAME	66	OST0 // 好感度
DEFINE_GFC_NAME	67	OST1
DEFINE_GFC_NAME	68	OST2 1 // この冒険で話したかどうか AREACHANGE 時に初期化
DEFINE_GFC_NAME	69	OST3 2


GFC_SEPARATOR 70 コーヒーメーカー

DEFINE_GFC_NAME	70	COF0 // 好感度
DEFINE_GFC_NAME	71	COF2 
GFC_SEPARATOR 72 徘徊チルダ
DEFINE_GFC_NAME	72	TLD_N0 // 好感度
DEFINE_GFC_NAME	73	TLD_N2 
DEFINE_GFC_NAME	74	TLD_NT // 服ビリ進行
GFC_SEPARATOR 75 徘徊木偶
DEFINE_GFC_NAME	75	PUP0  // 徘徊木偶
DEFINE_GFC_NAME	76	PUP2 
DEFINE_GFC_NAME	77	PUP_KILL  // キルカウント 奇数だと PuppetNpc が登場しない (店主を殺害後、戦闘が開始する状態)
DEFINE_GFC_NAME	78	PUP_KILL_BP  // バトルフェーズ
DEFINE_GFC_NAME	79	PUP_BUYR  // 購入金額倍率

GFC_SEPARATOR 80 グラティア関連
DEFINE_GFC_NAME	80	DJO0 // 道場
DEFINE_GFC_NAME	81	DFM0 // 酪農家
DEFINE_GFC_NAME	82	DFMT // 牛の疲労ゲージ
DEFINE_GFC_NAME	83	MUS0 // グラティア
DEFINE_GFC_NAME	84	WLR_G // グラティア酒場でのヴァーロスイベント
DEFINE_GFC_NAME	85	WLR_H // グラティア穴でのヴァーロスとの遭遇
DEFINE_GFC_NAME	86	BRT0 // バーテンダー
DEFINE_GFC_NAME	87	BRTU // バーテンダー



DEFINE_GFC_NAME 100 PVV0_KILLED
DEFINE_GFC_NAME 101 MEPHA
DEFINE_GFC_NAME 102 STATIONMAN
// theroom
DEFINE_GFC_NAME 103 TRM0
