---@type ChadrcConfig
local M = {}

-- Path to overriding theme and highlights files
local highlights = require "custom.highlights"

M.ui = {
  theme = "myrose",
  theme_toggle = { "myrose", "one_light" },

  hl_override = {
    LineNr = { fg = "base04" },
    CursorLine = { bg = "lightbg" },
    CursorColumn = { bg = "lightbg" },
    NvDashAscii = { fg = "#b8dceb", bg = "darker_black" },
    NvDashButtons = { fg = "black", bg = "#b8dceb" },

  -----------------------------------------------------------------------
  --syntax
  Boolean = { fg = "pink" },
  -- Character = { fg = "white" },
  -- Conditional = { fg = theme.base0E },
  Constant = { fg = "red" },
  -- Define = { fg = theme.base0E, sp = "none" },
  -- Delimiter = { fg = "white" },
  -- Float = { fg = theme.base09 },
  Variable = { fg = "white" },
  -- Function = { fg = "pink", bold = true, italic = false },
  -- Identifier = { },
  Include = { fg = "teal" },
  Keyword = { fg = "teal" },
  -- Label = { fg = theme.base0A },
  Number = { fg = "vibrant_green" },
  Operator = { fg = "#908caa" },
  -- PreProc = { fg = "teal" },
  -- Repeat = { fg = theme.base0A },
  -- Special = { fg = theme.base0C },
  -- SpecialChar = { fg = theme.base0F },
  -- Statement = { fg = theme.base08 },
  -- StorageClass = { fg = theme.base0A },
  String = { fg = "vibrant_green" },
  -- Structure = { fg = theme.base0E },
  Tag = { fg = "cyan" },
  Todo = { fg = "vibrant_green", bold = true },
  Type = { fg = "cyan" },

  -----------------------------------------------------------------------
  --treesitter
  ["@variable"] = { fg = "purple", italic = false },
  ["@variable.builtin"] = { fg = "dark_purple" },
  ["@variable.parameter"] = { fg = "purple", italic = true },
  ["@variable.member"] = { fg = "dark_purple" },
  ["@variable.member.key"] = { fg = "dark_purple" },
  --
  ["@module"] = { fg = "teal", bold = true },
  -- ["@module.builtin"] = { fg = "baby_pink" },
  --
  ["@constant"] = { fg = "green", bold = false },
  ["@constant.builtin"] = { fg = "green", bold = false },
  ["@constant.macro"] = { fg = "green", bold = false },
  --
  ["@string"] = { fg = "vibrant_green", italic = true },
  -- ["@string.regex"] = { fg = theme.base0C },
  -- ["@string.escape"] = { fg = theme.base0C },
  -- ["@character"] = { fg = theme.base08 },
  -- -- ["@character.special"] = { fg = theme.base08 },
  ["@number"] = { fg = "vibrant_green" },
  -- ["@number.float"] = { fg = theme.base09 },
  --
  -- ["@annotation"] = { fg = theme.base0F },
  -- ["@attribute"] = { fg = theme.base0A },
  -- ["@error"] = { fg = theme.base08 },
  --
  -- ["@keyword.exception"] = { fg = theme.base08 },
  ["@keyword"] = { fg = "teal" },
  -- ["@keyword.function"] = { fg = theme.base0E },
  ["@keyword.return"] = { fg = "teal" },
  -- ["@keyword.operator"] = { fg = theme.base0E },
  -- ["@keyword.import"] = { link = "Include" },
  -- ["@keyword.conditional"] = { fg = theme.base0E },
  -- ["@keyword.conditional.ternary"] = { fg = theme.base0E },
  -- ["@keyword.repeat"] = { fg = theme.base0A },
  -- ["@keyword.storage"] = { fg = theme.base0A },
  -- ["@keyword.directive.define"] = { fg = theme.base0E },
  -- ["@keyword.directive"] = { fg = theme.base0A },
  --
  ["@function"] = { fg = "pink", bold = true, italic = false },
  -- ["@function.builtin"] = { fg = theme.base0D },
  ["@function.macro"] = { fg = "green", bold = true },
  -- ["@function.call"] = { fg = theme.base0D },
  ["@function.method"] = { fg = "pink", bold = false },
  ["@function.method.call"] = { fg = "pink", bold = false },
  -- ["@constructor"] = { fg = theme.base0C },
  --
  -- ["@operator"] = { fg = theme.base05 },
  -- ["@reference"] = { fg = "purple", italic = true },
  ["@punctuation.bracket"] = { fg = "white" },
  ["@punctuation.delimiter"] = { fg = "white" },
  -- ["@symbol"] = { fg = theme.base0B },
  ["@tag"] = { fg = "cyan" },
  -- ["@tag.attribute"] = { fg = theme.base08 },
  -- ["@tag.delimiter"] = { fg = theme.base0F },
  -- ["@text"] = { fg = theme.base05 },
  -- ["@text.emphasis"] = { fg = theme.base09 },
  -- ["@text.strike"] = { fg = theme.base0F, strikethrough = true },
  ["@type.builtin"] = { fg = "cyan" },
  -- ["@definition"] = { sp = theme.base04, underline = true },
  -- ["@scope"] = { bold = true },
  ["@property"] = { fg = "dark_purple" },
  --
  -- -- markup
  -- ["@markup.heading"] = { fg = theme.base0D },
  -- ["@markup.raw"] = { fg = theme.base09 },
  -- ["@markup.link"] = { fg = theme.base08 },
  -- ["@markup.link.url"] = { fg = theme.base09, underline = true },
  -- ["@markup.link.label"] = { fg = theme.base0C },
  -- ["@markup.list"] = { fg = theme.base08 },
  -- ["@markup.strong"] = { bold = true },
  -- ["@markup.underline"] = { underline = true },
  -- ["@markup.italic"] = { italic = true },
  -- ["@markup.strikethrough"] = { strikethrough = true },
  -- ["@markup.quote"] = { bg = base30.black2 },
  --
  -- ["@comment"] = { fg = base30.grey_fg },
  ["@comment"] = { italic = true },
  -- ["@comment.todo"] = { fg = base30.grey, bg = base30.white },
  -- ["@comment.warning"] = { fg = base30.black2, bg = theme.base09 },
  -- ["@comment.note"] = { fg = base30.black2, bg = base30.white },
  -- ["@comment.danger"] = { fg = base30.black2, bg = base30.red },
  --
  -- ["@diff.plus"] = { fg = base30.green },
  -- ["@diff.minus"] = { fg = base30.red },
  -- ["@diff.delta"] = { fg = base30.light_grey },
  },

  transparency = true,

  tabufline = {},

  nvdash = {
    load_on_startup = true,

    header = {
      -- "           ▄ ▄                   ",
      -- "       ▄   ▄▄▄     ▄ ▄▄▄ ▄ ▄     ",
      -- "       █ ▄ █▄█ ▄▄▄ █ █▄█ █ █     ",
      -- "    ▄▄ █▄█▄▄▄█ █▄█▄█▄▄█▄▄█ █     ",
      -- "  ▄ █▄▄█ ▄ ▄▄ ▄█ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄  ",
      -- "  █▄▄▄▄ ▄▄▄ █ ▄ ▄▄▄ ▄ ▄▄▄ ▄ ▄ █ ▄",
      -- "▄ █ █▄█ █▄█ █ █ █▄█ █ █▄█ ▄▄▄ █ █",
      -- "█▄█ ▄ █▄▄█▄▄█ █ ▄▄█ █ ▄ █ █▄█▄█ █",
      -- "    █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█ █▄█▄▄▄█    ",
"                       .::---::..                           ",
"                 .-----...   ..:::----.                     ",
"       +:=    :=-:                    --=:           :---=: ",
"     =:#-- .==.                      --..:=-      --:     + ",
"    -*--.-=:  :.                       -=-::=-  -=.       .=",
"   =..+.=:   -:                    ..    -:.:-+*..:: .:----.",
"    :::=.:  +.                      =:    .=--=:-+:-:.      ",
"     :-:-  =    :            .   .   =::---:=.:=-:-=.       ",
"    .=:: .+.   +     *      ::+. :=  .=-:-:-==  #:. :=-     ",
"    ==. :+    -: .* =+.     -=.-= -.  ++   +=--.-*    .--   ",
"   .=: .# .   + :-==:.-     --  .:-+  ==: .==.+-:=*     =.  ",
"   =.  *:.   .=.- -.  ==.   :=     -= ::=--==.+ :-++.  --   ",
"   *  =*     --=  .   :=-.  -.   .=.=-:---: ::+.. + =:=.    ",
"   + -%:=    =-  :+#+. :.:-.-. =##=    =    .++ = .+        ",
"   +.:@.*   .+      =%-    .. -*+:     *:   --= .* :=       ",
"   .-.@ +   -:-   +*-           .=+:   -+   =:-  @- -       ",
"    .-+::-  =-=                        ++  --+.:.*+.:=      ",
"     :+.=*- =.+                       .==:+.=-:==:.*.=      ",
"     *.-*:==-=--:          .        :-*  : =.==:+  +-=      ",
"     * +%::--   +---::         .:--:. #     =.==.   --      ",
"     + #=:-=.   -+ . -*=+::::::=:-:.=.#:=  .-#.=:           ",
"     :+-.#- *.  :%==-. .=  ..  +   :=+*-*: :=.= -:          ",
"     =: =.--:+--::--... -=---=+: ..-=.*. +.=  -- -:         ",
"    -:  +   :. :=  :=--..=:  :-.-=-.. #   .    %  =         ",
"    +: .=      .=     =:--+===-:=     #        %  =         ",
"    =.  *       *     -.:-:++--:=    .*       .* :-         ",
"     -=.--      +.:=*+*=. -=-*.+==--::=       +.=-          ",
"       ::.      --+.  :=:=-=+= .+ .-+-+:     .:-            ",
"                :*.=   + *:=+:=-.  :-:+                     ",
-- "░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░",
-- "░░░░░░░░░░░░░░░░░░▒▒▒▒▒░░░░░░░░░▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░",
-- "░░░░░░░▓▒▒░░░░▒▒▒░░░░░░░░░░░░░░░░░░░░░▒▒▒░░░░░░░░░░░░▒▒▒▒▒▒░",
-- "░░░░░▒▒▓▒▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░▒▒░░░░░░▒▒▒░░░░░▓░",
-- "░░░░▒▓▒▒░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒░░▒▒░░░░░░░░░▒",
-- "░░░▒░░▓░▒▒░░░▒░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░▒▓▓░░▒░░░▒▒▒▒▒░",
-- "░░░░░░▒▒░▒░░▓░░░░░░░░░░░░░░░░░░░░░░░▒░░░░░░▒▒▒▒░▒▓▒▒▒░░░░░░░",
-- "░░░░░▒▒▒▒░░▒░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒░▒░░▒▒▒▒▒░░░░░░░░",
-- "░░░░░▒▒▒░░▓░░░░▓░░░░░▓░░░░░░░░▓░░░▒░░░▒▒▒▒▒▒▒▒░░▓▒░░░▒▒░░░░░",
-- "░░░░▒▒░░░▓░░░░▒▒░░▓░▒▓░░░░░░▒▒░▒▒░▒░░░▓▓░░░▓▒▒▒░▒▓░░░░░▒▒░░░",
-- "░░░░▒░░░█░░░░░▓░░▒▒▒░░▒░░░░░▒▒░░░▒▒▓░░▒▒▒░░▒▒░▓▒░▒▓░░░░░▒░░░",
-- "░░░▒░░░▓░░░░░░▒░▒░▒░░░▒▒░░░░▒▒░░░░░▒▒░░░▒▒▒▒▒░▓░░▒▓▓░░░▒▒░░░",
-- "░░░▓░░▒▓░░░░░▒▒▒░░░░░░░▒▒░░░▒░░░░░▒░▒▒▒▒▒▒▒░▒░▓░░░▓░▒░▒░░░░░",
-- "░░░▓░▒█▒▒░░░░▒▒░░▒▓▓▓░░▒░░▒░▒░░▒█▓▒░░░░▒░░░░░▓▓░▒░░▓░░░░░░░░",
-- "░░░▓░▒█░▓░░░░▓░░░░░░▒█▒░░░░░░░▒▓▓▒░░░░░▓░░░░▒▒▒░░▓░▒▒░░░░░░░",
-- "░░░░▒░█░▓░░░▒▒▒░░░▓▓▒░░░░░░░░░░░░▒▓▒░░░▒▓░░░▒░▒░░█▒░▒░░░░░░░",
-- "░░░░░▒▓░▒▒░░▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░▓▓░░▒▒▓░▒░▓▓░░▒░░░░░░",
-- "░░░░░▒▓░▒▓▒░▒░▓░░░░░░░░░░░░░░░░░░░░░░░░▒▒░▓░▒▒░▒▒▒░▓░▒░░░░░░",
-- "░░░░░▓░▒▓░▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░▒▓░░▒░▒░▒▒▒▓░░▓▒▒░░░░░░",
-- "░░░░░▓░▓█▒▒▒▒░░░▓▒▒▒▒░░░░░░░░░░░▒▒▒▒░░█░░░░░▒░▒▒░░░░▒▒░░░░░░",
-- "░░░░░▓░▓▒▒▒▒░░░░▒▓░░░▒▓▒▓▒▒░▒▒▒▒░▒▒░▒░█░▒░░░▒▓░▒▒░░░░░░░░░░░",
-- "░░░░░░▓▒░▓▒░▓░░░░█▒▒▒░░░▒░░░░░░▓░░░▒▒▓▓▒▓▒░░▒░▒░▒▒░░░░░░░░░░",
-- "░░░░░▒▒░▒░▒▒▒▓▒▒▒░▒▒░░░░▒▒▒▒▒▒▓▒░░░▒▒░▓░░▓░▒░░▒▒░▒▒░░░░░░░░░",
-- "░░░░▒▒░░▓░░░▒░░░▒░░░▒▒▒░░▒▒░░▒▒░▒▒▒░░░█░░░░░░░░█░░▒░░░░░░░░░",
-- "░░░░▓░░░▒░░░░░░░▒░░░░░▒▒▒▒▓▒▒▒▒▒▒░░░░░█░░░░░░░░█░░▒░░░░░░░░░",
-- "░░░░▒░░░▓░░░░░░░▓░░░░░▒░▒▒▒▓▓▒▒▒▒░░░░░▓░░░░░░░░▓░▒▒░░░░░░░░░",
-- "░░░░░▒▒░▒▒░░░░░░▓░▒▒▓▓▓▒░░▒▒▒▓░▓▒▒▒▒░░▒░░░░░░░▓░▒▒░░░░░░░░░░",
-- "░░░░░░░░░░░░░░░░▒▒▓░░░░▒▒▒▒▒▓▒░░▓░░▒▓▒▓▒░░░░░░▒▒░░░░░░░░░░░░",
-- "░░░░░░░░░░░░░░░░░▓░▒░░░▓░▓▒▒▓▒▒▒░░░▒▒░▓░░░░░░░░░░░░░░░░░░░░░",
-- "                                                                                ",
-- "                          .`,II:Il:,::!li>!!:;,`.                               ",
-- "         .``          `;i:,`.                  .:Il,.                       .   ",
-- "         1.'<`    .,>I`                          . '\"~I'              '\":,I,\"}  ",
-- "      .;\"(j\";'  ^>i'                             `>\"...\";I'        `!l'.     :! ",
-- "      .] .\\  .<!\"                                  '-\"\"\"''l!     '?^          )'",
-- "    'i;-_^.'>:.   .i`                                ,i'`\"'`_\" 'l!. .'.       \":",
-- "    :` .\\.Il`.   \"+.                           '`     .!:..^^;~v. `\"` .'^;>;,,` ",
-- "     '^^'_\" `.  ;:                              !\"      ']`,'_`^\"~I\",,^`.       ",
-- "       .+^'I...]^    ..                          ;`'```. .?```~\"`_!,'           ",
-- "       ?.^, . ~'    .{      ^.        ..    `^   .j'..',ll'+'  ;_.  i],.        ",
-- "      ;^^\" ..[^     1'     .f`        [./;. .).   ,`~^\",\"',:}.. (<''  '~l.      ",
-- "     .?;^ .'{^     ^:  .|. ~;,        (:`.:\" 'i   .[-.   ].<^~`.`M`.    ':l`    ",
-- "     l^\"  `u. .    {. 'I]`;,.>        ]: .\";:\"\",   1;:   +'i`)';.,j`       ?`   ",
-- "    '[`  .)! `    '! .> ::`  } '      f\"     .`)   ,^t.'I\"'- {`'`:;c'     ,+    ",
-- "    ,i   ;t ..    +\".}. \"`   ,`('     /`       `(' ^`^:^.>;,';\" .)'I}:   \"~     ",
-- "    +\" .^M\" .    .t`}.        ]^;'    x      `` ?:^^:^:I,. ,`,;. ..} I:.<,      ",
-- "    ]. \")1 ,.    ,'[. ',v1,.  .[.^,.  x   .>uW{'  '.;.    .'[,;.~  :< .'        ",
-- "    ]`.^M<./.    }..    .^~t1\"  .  ^\"'< `}n?`       ['     `(,^ '_  <:          ",
-- "    :[ `B'`t     >i       '+u~.       . '!/tI.     .[}     >'/'  n! 'I`         ",
-- "    .{ `%'.|    .,>`    lMr:.              `_cj`   .,1.    - 1.  |f. '!         ",
-- "     `~.n`'['   `:.:    `.                    .    .i~'   !\"!+.  fn: .j.        ",
-- "      .l<`''[   `)\"i    . .                  ..     {!,  :>^(.`\".c'_\" I\"        ",
-- "       ,{ `!->. ^;.1                               '+.,,?` +^ -`^~ .r.?\"        ",
-- "       /''I{\".\\,'!i\":,              ^            `;/  \"` l`.].\\.}.  >^1`        ",
-- "      .r ^!&':'.),   `t\"\"'.                  ',!!`.x.     l^ .r.:   .`i'        ",
-- "      ') l|n`',,.    .|..`\"\":,```......``;\"~[`    `c.`    .I, -_     '\",        ",
-- "       { I/^`;']`    .?- `  ./'\"li'`''`..^~ \",\".,,:f.~.   :,c,.i,               ",
-- "       ^+,''u? ./.   .!/_:?\"`  `i        ._   .^-:81'j<  .\"!.1' \",              ",
-- "       ,_. ;`:;.`n;:. \"<\"` '.   I,'\":,,\"^). ...';`^}\" ;> :!   ?. Ii             ",
-- "      \",' .|  .-,;..i|' `:}` '.  ?,^```^_\".'.'!?\"..x. ._^:    ,[  l\"            ",
-- "      |. .'?    .'  .v.   .,l;`'..-.   :: `I!:.   `v          'M. .!            ",
-- "     'v.  ;^        .r.      !`,I,:[;`>i;;^;      \"r          .W. .~            ",
-- "     '1   `}         +,      `l  ',,+I^,\".^;      l}          `f  `:            ",
-- "      :,. 'n.        '|   '^\"^?',` :)I!^.`_.      +;          {`.,i             ",
-- "       '+I '!         ) \"~+~I+-i  `,?;.|'>>{]}!l,.?^         ?`.~\"              ",
-- "         .,`'         ['[^    {`,'>^}I`+ .\"! .',)`1:\"       .,\":.               ",
-- "                      <,.[    ^[ \";,}l,;, i.   `+ /,.                           ",
-- "                      ;] i\"    ^.IIl,\"l,_ -    I` !{                            ",
    },

    buttons = {
      { "  Find File", "Spc f f", "Telescope find_files" },
      { "󰈚  Recent Files", "Spc f o", "Telescope oldfiles" },
      { "󰈭  Find Word", "Spc f w", "Telescope live_grep" },
      { "  Bookmarks", "Spc m a", "Telescope marks" },
      { "  Themes", "Spc t h", "Telescope themes" },
      { "  Mappings", "Spc c h", "NvCheatsheet" },
    },
  },
}

M.plugins = "custom.plugins"

-- check core.mappings for table structure
M.mappings = require "custom.mappings"

return M
