PIC_HIDE_ALL	 
DENY_MSGLOG

GETITEM_NOANNOUNCE mtr_water0 1 0
GETITEM_NOANNOUNCE mtr_wheat 2 0
GETITEM_NOANNOUNCE mtr_lettuce 2 0
IF '!ItemHas[Recipe_sandwich]' {
    GETITEM_NOANNOUNCE Recipe_sandwich 1
}
IF '!ItemHas[Recipe_bread]' {
    GETITEM_NOANNOUNCE mtr_water0 1 0
    GETITEM_NOANNOUNCE mtr_wheat 2 0
    GETITEM_NOANNOUNCE Recipe_bread 1
}

HKDS	d RB @RBOUT
HKDS	n CRB @LBOUT

COOKING_TUTORIAL alchemy_cutin/f_tilde 
UICOOKING ARROW_IMG whole_general/arrow_r

UICOOKING TARGET sandwich
UICOOKING ALLOC_MULTIPLE_CREATION 0
MTL DENY_EVENTHANDLE
MTL MSG_HOLD
MTL UICOOKING WAIT RECIPE_CHOOSE_ROW

MSG	d_00
ALLOW_EVENTHANDLE


UICOOKING TARGET_INGREDIENT 1 
MTL DENY_EVENTHANDLE
MTL MSG_HOLD
MTL UICOOKING WAIT RECIPE_CHOOSE_ROW_AUTO

MSG	d_01
ALLOW_EVENTHANDLE



MTL DENY_EVENTHANDLE
MTL MSG_HOLD
MTL UICOOKING WAIT ING_AUTO_FINISHED

MSG	d_03
UICOOKING TARGET_INGREDIENT -1
ALLOW_EVENTHANDLE


MSG	d_04

UICOOKING TARGET_INGREDIENT 2

MTL DENY_EVENTHANDLE
MTL MSG_HOLD
MTL UICOOKING WAIT ING_CONTENT_OR_AUTO

MSG	d_05

MSG_HIDE
UICOOKING TARGET_INGREDIENT -1
UICOOKING WAIT RECIPE_CHOOSE_ROW_FILLED_ALLOW_AUTO


MTL DENY_EVENTHANDLE
MTL MSG_HOLD
MTL UICOOKING WAIT COMPLETED_ALLOW_AUTO
MSG	d_06
ALLOW_EVENTHANDLE
MSG_HIDE
WAIT 60

MSG	d_07


DENY_EVENTHANDLE
UICOOKING WAIT RECIPE_CHOOSE_ROW
ALLOW_EVENTHANDLE

WAIT 20
UICOOKING DEACTIVATE

WAIT 20
ALLOW_MSGLOG
CHANGE_EVENT	___Tilde/cook_tuto03
